import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { SubscribeToNewsletterForm } from "../components/shared/forms/SubscribeToNewsletterForm";
import styles from "styles/Content.module.css";
import fontStyles from "styles/fontStyles.module.css";

const Content: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles["container"]}>
          <div className={styles["inner-container"]}>
            <h1 className={`${fontStyles["title-header"]}`}>
              Content in the works.
            </h1>
            <h2
              className={`${fontStyles["title-header"]} ${styles["subtitle-text"]}`}
            >
              Subscribe to our newsletter.
            </h2>
            <div className={styles["details-container"]}>
              <p
                className={`${fontStyles["body-copy"]} ${styles["body-text"]}`}
              >
                Sign up to recieve all the latets news and content. We regularly
                create podcasts, videos , and articles in order to keep the
                conversation growing.
              </p>
              <div className={styles["subscribe-section"]}>
                <SubscribeToNewsletterForm />
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Content;
