import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { ContactForm } from "../components/shared/forms/ContactForm";
import styles from "styles/Contact.module.css";
import fontStyles from "styles/fontStyles.module.css";
import Image from "next/image";

const Contact: NextPage = () => {
  const router = useRouter();

  const backHandler = () => {
    router.back();
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className={styles["container"]}>
            <div className={styles["inner-container"]}>
              <button onClick={backHandler} className={styles["button"]}>
                <Image
                  src="/arrows/leftArrowBeige.svg"
                  alt="Go"
                  width={24}
                  height={24}
                />
                <p className={fontStyles["flair-copy"]}>Back</p>
              </button>
            </div>
          </div>
          <ContactForm />
        </div>
      </main>
    </div>
  );
};

export default Contact;
