import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { SubscribeToNewsletterForm } from "../components/shared/forms/SubscribeToNewsletterForm";

const Content: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Content in the works.</h1>
        <div>
          <div>
            <h2>Subscribe to our newsletter.</h2>
            <p>
              Sign up to recieve all the latets news and content. We regularly
              create podcasts, videos , and articles in order to keep the
              conversation growing.
            </p>
          </div>
          <div>
            <SubscribeToNewsletterForm />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Content;
