import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { ContactForm } from "../components/shared/forms/ContactForm";

const Contact: NextPage = () => {
  const router = useRouter();

  const backHandler = () => {
    router.back();
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button onClick={backHandler}>Back</button>
          <ContactForm />
        </div>
      </main>
    </div>
  );
};

export default Contact;
