import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Services: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Services Page</h1>
      </main>
    </div>
  );
};

export default Services;
