import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ServiceSection } from "../components/pages/servicePage/ServiceSection";
import { Subheading } from "../components/shared/navbars/Subheading";
import { BetterSumColors } from "../types/BetterSumColors";
import styles from "../styles/Services.module.css";
import {
  ServiceOptions,
  ServicePageContextProvider,
} from "../contexts/servicePageContext";

const Services: NextPage = () => {
  const StrategyOverview = (
    <p>
      Our work begins at the inception of an idea. We solve problems, challenge
      values, and develop strategies to articulate a <b>better</b> point of view
      that helps your business{" "}
      <span className={styles["highlighted-text"]}>navigate the future</span>.
    </p>
  );

  const DesignOverview = (
    <p>
      We design digital products, brands, and services by building{" "}
      <span className={styles["highlighted-text"]}>with empathy</span>. We
      believe that a thoughtful user experience is what makes the difference
      between a great solution and a <b>better</b> solution.
    </p>
  );

  const DevelopmentOverview = (
    <p>
      We help transform great visions into <b>better</b> products. We expand
      your ideas into{" "}
      <span className={styles["highlighted-text"]}>
        fully functioning products,
      </span>{" "}
      that quickly obtain user feedback for focusing on developing the next
      steps for your business.
    </p>
  );

  return (
    <ServicePageContextProvider>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <div>
            <Subheading title="All Services" color={BetterSumColors.OffBlack} />
            <h1>
              Integrated capabilities across strategy, design and development.
            </h1>
            <div>
              <ServiceSection
                index={1}
                type={ServiceOptions.strategy}
                title="Strategy"
                overview={StrategyOverview}
                services={[]}
              />
              <ServiceSection
                index={2}
                type={ServiceOptions.design}
                title="Holistic Design"
                overview={DesignOverview}
                services={[]}
              />
              <ServiceSection
                index={3}
                type={ServiceOptions.development}
                title="Development"
                overview={DevelopmentOverview}
                services={[]}
              />
            </div>
          </div>
        </main>
      </div>
    </ServicePageContextProvider>
  );
};

export default Services;
